version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - minio
    ports:
      - '${APP_PORT}:$${APP_PORT}'
    environment:
      - MONGO_URI=${MONGO_URI}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    networks:
      - network-backend
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ~/mongo/data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    env_file:
      - .env.db
    ports:
      - 27017:27017
    networks:
      - network-backend
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - network-backendo
    command: server /data --console-address ":9090"
