version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - minio
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    networks:
      - network-backend
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ~/mongo/data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    env_file:
      - .env.db
    ports:
      - 27017:27017
    networks:
      - network-backend
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env.db
    command: server /data --console-address ":9090"
